#:import FD python_files.files_path.FileDirectories
#:import NoTransition kivy.uix.screenmanager.NoTransition

MainManager:
    transition: NoTransition()
    Screen:
        id: presplash
        name: "presplash"
        BoxLayout:
            orientation: 'vertical'
            Image:
                source: FD.presplash
                allow_stretch: True
    
    Screen:
        id: manager_screen
        name: "manager_screen"
        
            
                   
    